### ISSUE TITLE
root not having a z-index causes .autocomplete-container to be hidden by other relatively positioned elements

### ISSUE THREAD

**Issue by leoi11** [kenny-hibino/react-places-autocomplete#95]
I found a UI issue when there is a relatively positioned element below the autocomplete input.
I am not familiar with z-index but my guess is when 2 elements (e.g. root and another element A) are rendered with `position: relative`, they implicitly shares the same z-index, but when there is a child of one of these elements (`.autocomplete-container` in this case) and the child overlaps with element A, then element A will be on top of the `.autocomplete-container`.

This was solved in my code by introduce an explicit z-index on the root element that is 1 or greater.

I wonder if having an explicit z-index in the default style for root would be a reasonable solution.

(Btw, Thanks for writing this library. It's the best out there we found, and we're contented with it so far.)

**Comment by daose** [comment]
In my case I had to put it on `autocompleteContainer`, not `root`. Mine ended up looking like this:

```jsx
<PlacesAutocomplete
    classNames={{ autocompleteContainer: 'ac-container' }}
    {...otherProps}
/>
```
```css
.ac-root {
  position: absolute;
  top: 100%;
  backgroundColor: white;
  border: 1px solid #555555;
  width: 100%;
  z-index: 1000;
}
```
